apiVersion: v1
kind: Service
metadata:
  name: springboot-helloworld
  labels:
    app: springboot-helloworld
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: springboot-helloworld
  type: NodePort